---
title: A02 Regression Models
author: ''
date: '2022-03-26'
slug: regression-models
categories: []
tags: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<pre class="r"><code>library(ISLR)</code></pre>
<pre><code>## Warning: package &#39;ISLR&#39; was built under R version 4.1.3</code></pre>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --</code></pre>
<pre><code>## v ggplot2 3.3.5     v purrr   0.3.4
## v tibble  3.1.6     v dplyr   1.0.7
## v tidyr   1.2.0     v stringr 1.4.0
## v readr   2.1.2     v forcats 0.5.1</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(boot)

diamond_data &lt;- read_csv(&quot;https://raw.githubusercontent.com/rkavalakatt/website_delete/main/content/post/2022-03-26-regression-models/Professor_Proposes_Data.csv&quot;)</code></pre>
<pre><code>## Rows: 440 Columns: 9</code></pre>
<pre><code>## -- Column specification --------------------------------------------------------
## Delimiter: &quot;,&quot;
## chr (6): Colour, Clarity, Cut, Certification, Polish, Symmetry
## dbl (3): Carat, Price, Wholesaler
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>attach(diamond_data)
head(diamond_data)</code></pre>
<pre><code>## # A tibble: 6 x 9
##   Carat Colour Clarity Cut   Certification Polish Symmetry Price Wholesaler
##   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;
## 1  0.92 I      SI2     G     AGS           V      V         3000          1
## 2  0.92 I      SI2     V     AGS           G      G         3000          1
## 3  0.82 F      SI2     I     GIA           X      X         3004          1
## 4  0.81 G      SI1     I     GIA           X      V         3004          1
## 5  0.9  J      VS2     V     GIA           V      V         3006          1
## 6  0.87 F      SI2     I     AGS           G      V         3007          1</code></pre>
<pre class="r"><code>###COunt of each variable
diamond_data %&gt;% count(Carat)</code></pre>
<pre><code>## # A tibble: 50 x 2
##    Carat     n
##    &lt;dbl&gt; &lt;int&gt;
##  1  0.09     5
##  2  0.1     13
##  3  0.11     5
##  4  0.2      1
##  5  0.21     7
##  6  0.22     5
##  7  0.23     7
##  8  0.27     1
##  9  0.28     2
## 10  0.3    154
## # ... with 40 more rows</code></pre>
<pre class="r"><code>diamond_data %&gt;% count(Cut)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   Cut       n
##   &lt;chr&gt; &lt;int&gt;
## 1 F        59
## 2 G        49
## 3 I        86
## 4 V        97
## 5 X       149</code></pre>
<pre class="r"><code>diamond_data %&gt;% count(Clarity)</code></pre>
<pre><code>## # A tibble: 9 x 2
##   Clarity     n
##   &lt;chr&gt;   &lt;int&gt;
## 1 I1         82
## 2 I2         28
## 3 SI1       116
## 4 SI2       110
## 5 SI3        26
## 6 VS1        30
## 7 VS2        41
## 8 VVS1        2
## 9 VVS2        5</code></pre>
<pre class="r"><code>diamond_data %&gt;% count(Certification)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   Certification     n
##   &lt;chr&gt;         &lt;int&gt;
## 1 AGS              12
## 2 DOW               1
## 3 EGL             119
## 4 GIA             265
## 5 IGI              43</code></pre>
<pre class="r"><code>diamond_data %&gt;% count(Symmetry)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   Symmetry     n
##   &lt;chr&gt;    &lt;int&gt;
## 1 F           21
## 2 G          157
## 3 I            5
## 4 V          206
## 5 X           51</code></pre>
<pre class="r"><code>diamond_data %&gt;% count(Price)</code></pre>
<pre><code>## # A tibble: 197 x 2
##    Price     n
##    &lt;dbl&gt; &lt;int&gt;
##  1   160     6
##  2   180    11
##  3   190     5
##  4   320     2
##  5   330     6
##  6   340     6
##  7   360     5
##  8   372     1
##  9   404     1
## 10   439     1
## # ... with 187 more rows</code></pre>
<pre class="r"><code>diamond_data %&gt;% count(Wholesaler)</code></pre>
<pre><code>## # A tibble: 3 x 2
##   Wholesaler     n
##        &lt;dbl&gt; &lt;int&gt;
## 1          1    60
## 2          2   180
## 3          3   200</code></pre>
<pre class="r"><code>## Make graphs of the frequency of each of the variables

###Bar chart of Carat
diamond_data %&gt;%
  ggplot() +
  geom_bar(aes(Carat, fill = Carat)) +
   theme(legend.position = &quot;none&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>###Bar chart of Colour
diamond_data %&gt;%
  ggplot() +
  geom_bar(aes(Colour, fill = Colour)) +
  theme(legend.position = &quot;none&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-2.png" width="672" /></p>
<pre class="r"><code>###Bar chart of Cut
diamond_data %&gt;%
  ggplot() +
  geom_bar(aes(Cut, fill = Cut)) +
  theme(legend.position = &quot;none&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-3.png" width="672" /></p>
<pre class="r"><code>###Bar chart of Clarity
diamond_data %&gt;%
  ggplot() +
  geom_bar(aes(Clarity, fill = Clarity)) +
  theme(legend.position = &quot;none&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-4.png" width="672" /></p>
<pre class="r"><code>###Bar chart of Certification
diamond_data %&gt;%
  ggplot() +
  geom_bar(aes(Certification, fill = Certification)) +
  theme(legend.position = &quot;none&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-5.png" width="672" /></p>
<pre class="r"><code>###Bar chart of Polish
diamond_data %&gt;%
  ggplot() +
  geom_bar(aes(Polish, fill = Polish)) +
  theme(legend.position = &quot;none&quot;
  )</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-6.png" width="672" />
### From the frequency graphs, we can see that there are two main clusters of carat size represented in the data, one under 0.1-0.3 Carat, and one above 0.8 Carat.</p>
<pre class="r"><code>### Plot of Price vs Frequency
ggplot(diamond_data, aes(x = Price)) +
  geom_freqpoly(binwidth = 50)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-3-1.png" width="672" />
### There are two clusters of prices, below $1000 and above $2000 dollars. Next, we should see if cluster size is related to price.</p>
<pre class="r"><code># Create dichotomous variable for ideal cut or higher
diamond_data %&lt;&gt;%
  mutate(
    diamond_cut = case_when(
      Cut %in%
        c(&quot;F&quot;,
          &quot;G&quot;) ~
          &quot;less than ideal&quot;,
      Cut %in%
        c(&quot;I&quot;,
          &quot;V&quot;,
          &quot;X&quot;) ~
          &quot;more than ideal&quot;,
      Cut == &quot;NA&quot; ~ &quot;NA&quot;)
  ) %&gt;%
  print()</code></pre>
<pre><code>## # A tibble: 440 x 10
##    Carat Colour Clarity Cut   Certification Polish Symmetry Price Wholesaler
##    &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;
##  1  0.92 I      SI2     G     AGS           V      V         3000          1
##  2  0.92 I      SI2     V     AGS           G      G         3000          1
##  3  0.82 F      SI2     I     GIA           X      X         3004          1
##  4  0.81 G      SI1     I     GIA           X      V         3004          1
##  5  0.9  J      VS2     V     GIA           V      V         3006          1
##  6  0.87 F      SI2     I     AGS           G      V         3007          1
##  7  0.8  D      SI2     I     GIA           V      V         3008          1
##  8  0.84 F      SI1     G     GIA           V      V         3010          1
##  9  0.8  D      SI2     V     GIA           V      V         3012          1
## 10  0.8  D      SI2     V     GIA           V      X         3012          1
## # ... with 430 more rows, and 1 more variable: diamond_cut &lt;chr&gt;</code></pre>
<pre class="r"><code>### get count for avg_cut
diamond_data %&gt;% count(diamond_cut)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   diamond_cut         n
##   &lt;chr&gt;           &lt;int&gt;
## 1 less than ideal   108
## 2 more than ideal   332</code></pre>
<pre class="r"><code>### Plot of Price vs Carat size, with avg_cut overlaid
diamond_data %&gt;%
  filter(!is.na(diamond_cut)) %&gt;%
  ggplot(aes(x = Carat, y = Price, fill = diamond_cut, color = diamond_cut)) + 
  geom_point()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-4-1.png" width="672" />
### We can tell from this graph that there are two distict clusters of diamonds, one of low carat diamonds at a low price range, and one of high carat diamonds at a higher price range. From this, we can tell that Carat size is a large predictor of diamond price.</p>
<div id="additionally-through-dichotomizing-the-cut-variable-we-can-see-that-cut-is-not-a-great-predictor-of-price-as-there-were-expensive-diamonds-that-had-both-a-more-than-ideal-cut-and-a-less-than-ideal-cut.-thus-we-can-tell-that-cut-is-not-a-huge-predictor-of-diamond-price." class="section level3">
<h3>Additionally, through dichotomizing the cut variable, we can see that cut is not a great predictor of price, as there were expensive diamonds that had both a more than ideal cut and a less than ideal cut. Thus, we can tell that Cut is not a huge predictor of diamond price.</h3>
<pre class="r"><code># Create dichotomous variable for ideal polish or higher
diamond_data %&lt;&gt;%
  mutate(
    avg_polish = case_when(
      Polish %in%
        c(&quot;F&quot;,
          &quot;G&quot;) ~
          &quot;no&quot;,
      Polish %in%
        c(&quot;I&quot;,
          &quot;V&quot;,
          &quot;X&quot;) ~
          &quot;yes&quot;,
      Polish == &quot;NA&quot; ~ &quot;NA&quot;)
  ) %&gt;%
  print()</code></pre>
<pre><code>## # A tibble: 440 x 11
##    Carat Colour Clarity Cut   Certification Polish Symmetry Price Wholesaler
##    &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;
##  1  0.92 I      SI2     G     AGS           V      V         3000          1
##  2  0.92 I      SI2     V     AGS           G      G         3000          1
##  3  0.82 F      SI2     I     GIA           X      X         3004          1
##  4  0.81 G      SI1     I     GIA           X      V         3004          1
##  5  0.9  J      VS2     V     GIA           V      V         3006          1
##  6  0.87 F      SI2     I     AGS           G      V         3007          1
##  7  0.8  D      SI2     I     GIA           V      V         3008          1
##  8  0.84 F      SI1     G     GIA           V      V         3010          1
##  9  0.8  D      SI2     V     GIA           V      V         3012          1
## 10  0.8  D      SI2     V     GIA           V      X         3012          1
## # ... with 430 more rows, and 2 more variables: diamond_cut &lt;chr&gt;,
## #   avg_polish &lt;chr&gt;</code></pre>
<pre class="r"><code>### get count for avg_cut
diamond_data %&gt;% count(avg_polish)</code></pre>
<pre><code>## # A tibble: 3 x 2
##   avg_polish     n
##   &lt;chr&gt;      &lt;int&gt;
## 1 no           170
## 2 yes          269
## 3 &lt;NA&gt;           1</code></pre>
<pre class="r"><code>### Plot of Price vs Polish
diamond_data %&gt;%
  filter(!is.na(avg_polish)) %&gt;%
  ggplot(aes(x = Wholesaler, y = Price, fill = avg_polish, color = avg_polish)) + 
  geom_point()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>diamond_data %&gt;%
  ggplot(aes(x = Polish, y = Price)) + 
  geom_point()</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-5-2.png" width="672" />
## We can see that polish does not seem to correlate with price point that much, as there are diamonds of different polishes at all price points.
## Wholesaler 1 seems to have the highest quality of polish among the three sellers.</p>
<pre class="r"><code>##Linear Regression Model w all variables

all.lm.fit &lt;- lm(Price~Carat + Colour + Clarity + Cut + Certification + Polish + Symmetry, data = diamond_data)
summary(all.lm.fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Price ~ Carat + Colour + Clarity + Cut + Certification + 
##     Polish + Symmetry, data = diamond_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -762.63  -82.58  -18.59  101.42  689.59 
## 
## Coefficients: (1 not defined because of singularities)
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      -1432.6219   146.6961  -9.766  &lt; 2e-16 ***
## Carat             4205.3391    51.2981  81.978  &lt; 2e-16 ***
## ColourE           -191.2462    53.5345  -3.572 0.000396 ***
## ColourF           -311.1620    53.6267  -5.802 1.32e-08 ***
## ColourG           -301.4412    54.5157  -5.529 5.76e-08 ***
## ColourH           -430.3664    53.0617  -8.111 6.03e-15 ***
## ColourI           -500.9400    53.0827  -9.437  &lt; 2e-16 ***
## ColourJ           -635.8407    54.6431 -11.636  &lt; 2e-16 ***
## ColourK           -985.9734    61.0240 -16.157  &lt; 2e-16 ***
## ColourL          -1173.6677    76.3472 -15.373  &lt; 2e-16 ***
## ClarityI2         -778.3139    50.8010 -15.321  &lt; 2e-16 ***
## ClaritySI1         858.5738    43.2466  19.853  &lt; 2e-16 ***
## ClaritySI2         731.5613    35.6145  20.541  &lt; 2e-16 ***
## ClaritySI3         388.9407    49.2119   7.903 2.58e-14 ***
## ClarityVS1        1025.1681    59.0373  17.365  &lt; 2e-16 ***
## ClarityVS2         915.4216    53.2913  17.178  &lt; 2e-16 ***
## ClarityVVS1       1342.8683   154.7169   8.680  &lt; 2e-16 ***
## ClarityVVS2        918.2219   101.0745   9.085  &lt; 2e-16 ***
## CutG                56.4835    41.8846   1.349 0.178233    
## CutI                95.4908    40.9225   2.333 0.020112 *  
## CutV                84.1675    41.5654   2.025 0.043527 *  
## CutX                56.8290    35.7071   1.592 0.112269    
## CertificationDOW  -500.9363   223.5204  -2.241 0.025558 *  
## CertificationEGL  -418.0748    81.9208  -5.103 5.13e-07 ***
## CertificationGIA   -64.8962    80.6771  -0.804 0.421640    
## CertificationIGI     0.2533    94.8367   0.003 0.997871    
## PolishG            210.9384   106.7503   1.976 0.048832 *  
## PolishI            461.4891   156.8392   2.942 0.003443 ** 
## Polishv            265.1641   230.8040   1.149 0.251286    
## PolishV            226.5659   110.6450   2.048 0.041234 *  
## PolishX            236.0952   113.7270   2.076 0.038524 *  
## SymmetryG          108.1495    57.3953   1.884 0.060239 .  
## SymmetryI                NA         NA      NA       NA    
## SymmetryV          119.4279    61.2390   1.950 0.051841 .  
## SymmetryX          113.5676    68.3626   1.661 0.097435 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 197.2 on 406 degrees of freedom
## Multiple R-squared:  0.974,  Adjusted R-squared:  0.9719 
## F-statistic: 460.4 on 33 and 406 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>##The R squared value of this model is 0.972, so this is a very accurate linear regression model.
## Coduct an Anova test in order to see which variables are the most significant predictors of price</p>
<pre class="r"><code>anova(all.lm.fit, test=&quot;Chisq&quot;)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: Price
##                Df    Sum Sq   Mean Sq    F value    Pr(&gt;F)    
## Carat           1 519687583 519687583 13360.8061 &lt; 2.2e-16 ***
## Colour          8  10605862   1325733    34.0837 &lt; 2.2e-16 ***
## Clarity         8  53866928   6733366   173.1102 &lt; 2.2e-16 ***
## Cut             4   1395625    348906     8.9701 5.978e-07 ***
## Certification   4   4806401   1201600    30.8923 &lt; 2.2e-16 ***
## Polish          5    498784     99757     2.5647   0.02666 *  
## Symmetry        3    152390     50797     1.3059   0.27204    
## Residuals     406  15791948     38896                         
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="looking-at-the-prf-tells-us-the-p-value-or-the-significance-associated-with-each-of-the-variables.-from-the-anova-test-we-can-tell-that-carat-colour-clarity-and-cut-have-the-greatest-significance-when-it-comes-to-predicting-diamond-price-and-so-these-will-be-the-variables-that-we-include-in-our-linear-regression-model." class="section level3">
<h3>Looking at the Pr(&gt;F) tells us the p value, or the significance, associated with each of the variables. From the Anova test, we can tell that Carat, Colour, Clarity, and Cut have the greatest significance when it comes to predicting diamond price, and so these will be the variables that we include in our linear regression model.</h3>
<pre class="r"><code>##regression model using Carat, Colour and Clarity
model &lt;- lm(Price~Carat + Colour + Clarity + Cut, data = diamond_data)

summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Price ~ Carat + Colour + Clarity + Cut, data = diamond_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -871.84 -113.74  -30.85  153.66  758.43 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1262.96      75.10 -16.817  &lt; 2e-16 ***
## Carat        4021.16      47.87  84.007  &lt; 2e-16 ***
## ColourE      -222.88      60.13  -3.707 0.000238 ***
## ColourF      -326.58      59.66  -5.474 7.59e-08 ***
## ColourG      -267.34      61.47  -4.349 1.72e-05 ***
## ColourH      -455.52      58.73  -7.756 6.75e-14 ***
## ColourI      -512.56      58.61  -8.746  &lt; 2e-16 ***
## ColourJ      -729.74      60.22 -12.119  &lt; 2e-16 ***
## ColourK     -1004.86      68.61 -14.645  &lt; 2e-16 ***
## ColourL     -1138.90      86.13 -13.224  &lt; 2e-16 ***
## ClarityI2    -593.78      50.17 -11.835  &lt; 2e-16 ***
## ClaritySI1    955.49      46.18  20.691  &lt; 2e-16 ***
## ClaritySI2    812.39      38.59  21.052  &lt; 2e-16 ***
## ClaritySI3    236.55      52.83   4.477 9.77e-06 ***
## ClarityVS1   1187.11      61.77  19.219  &lt; 2e-16 ***
## ClarityVS2   1039.77      56.81  18.304  &lt; 2e-16 ***
## ClarityVVS1  1431.16     173.41   8.253 2.04e-15 ***
## ClarityVVS2  1031.59     111.48   9.254  &lt; 2e-16 ***
## CutG          103.69      45.47   2.280 0.023083 *  
## CutI          190.10      41.93   4.533 7.59e-06 ***
## CutV          204.53      43.15   4.740 2.93e-06 ***
## CutX          150.08      36.85   4.073 5.54e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 225.5 on 418 degrees of freedom
## Multiple R-squared:  0.965,  Adjusted R-squared:  0.9632 
## F-statistic: 548.5 on 21 and 418 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>##Conduct the regression model using our professor&#39;s given data
professors_ring &lt;- data.frame(Carat = 0.9, Colour = &quot;J&quot;, Clarity = &quot;SI2&quot;, Cut = &quot;V&quot;, Certification = &quot;GIA&quot;, Polish = &quot;G&quot;, Symmetry = &quot;V&quot;)

predict(model, professors_ring)</code></pre>
<pre><code>##       1 
## 2643.27</code></pre>
</div>
<div id="the-professor-should-be-paying-around-2643.27-for-his-ring-although-this-does-not-include-the-price-of-the-ring-only-the-diamond.-the-price-of-3100-that-he-was-given-for-his-ring-of-interest-is-too-high-and-he-may-be-being-overcharged.-the-professor-should-budget-around-2800---3000-for-his-diamond-ring-depending-on-how-fancy-of-a-ring-band-he-wants." class="section level3">
<h3>The professor should be paying around $2643.27 for his ring, although this does not include the price of the ring, only the diamond. The price of $3100 that he was given for his ring of interest is too high and he may be being overcharged. The professor should budget around $2800 - $3000 for his diamond ring, depending on how fancy of a ring band he wants.</h3>
<pre class="r"><code>## Second method: Bootstrapping

set.seed(1)

boot.fn &lt;- function(data, index) {
  return(coef(lm(Price~Cut + Carat, data = diamond_data, subset = index)))
}

boot.out &lt;- boot(diamond_data, boot.fn, 500)
plot(boot.out)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>set.seed(1)

boot.fn &lt;- function(data, index) {
  return(coef(lm(Price~Cut + Carat, data = diamond_data, subset = index)))
}

boot.out &lt;- boot(diamond_data, boot.fn, 500)
plot(boot.out)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
